In [21]:
#### **IMPORTANDO LIBRERIA NUMPY**
import numpy as np

In [22]:
### CREANDUN UNA LISTA ###
list_gods = [1,2,3,4,5,6,7,8,9,10]
list_gods

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [23]:
### TRANDFORMANDO LA LISTA A UNA ARRAY ###
arreglo = np.array(list_gods)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
### VERIFICAR EL TIPO DE ESTRUCTURA ###
type(arreglo)

numpy.ndarray

In [25]:
### VERIFICAR LOS TIPOS DE DATOS DEL ARREGLO ###
arreglo.dtype

dtype('int32')

In [34]:
### DEFINIENDO EL ARRAY DE INT32 A FLOAT32 ###
np.array(arreglo, dtype=np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [37]:
### TRANSFORMANDO LOS DATOS DE INT32 A FLOAT32 ###
arreglo.astype(np.float32)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=float32)

In [38]:
### FUNCION SIMILAR A RANGE PERO USANDO ARREGLOS ###
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
### ARREGLO DE 2 EN 2 USANDO ARANGE ###
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

In [40]:
### FUNCIONES EN NUMPY ###
### OBTENIEDO EL PROMEDIO EL ARRAY ###

promedio = np.mean(arreglo)
promedio

5.5

In [41]:
### OBTENIENDO LA MEDIANA ###
mediana = np.median(arreglo)
mediana

5.5

In [42]:
### DESVIACION ESTANDAR DE UN ARREGLO ###
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

In [49]:
### GENERACION DE UN ARREGLO DE 5 ELEMENTOS DE PUROS CEROS ###
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

In [50]:
### GENERACION DE UN ARREGLO DE 10 ELEMENTOS DE PUROS UNOS ###
arreglo_de_unos = np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [48]:
### TRANSFORMANDO EL ARREGLO DE UNOS DE PUNTO FLOTANTES A ENTEROS ###
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [53]:
### GENERANDO ARREGLO ALEATORIO DE 5 ELEMENTOS ###
arreglo_aleatorio = np.random.rand(5)
arreglo_aleatorio

array([0.11537138, 0.06042701, 0.07589146, 0.32189933, 0.13935706])

In [54]:
### GENERANDO UNA AMTRIZ ALEATORIA DE 3X3 ###
matriz = np.random.rand(3,3)
matriz

array([[0.80303615, 0.22047768, 0.4176476 ],
       [0.04440256, 0.74609332, 0.27427931],
       [0.36948645, 0.72879061, 0.5567617 ]])

In [57]:
### GENERANDO UN ARREGLO ALEATORIO DE 10 NUMEROS ENTEROS DE 1 AL 5 ###
arreglo_aleatorio2 = np.random.randint(1,5,10)
arreglo_aleatorio2

array([3, 3, 3, 4, 2, 4, 2, 3, 4, 1])

In [ ]:
### GENERANDO UNA MATRIZ ALEATORIA DE 5 ELEMENTOS ENTEROS DE 1 AL 100 ###
matriz2 = np.random.randint(1,100(5,5))
matriz2