<h3><b>IMPORTANDO LIBRERIA NUMPY</b></h3>

In [1]:
import numpy as np

<h3><b>CREANDO UNA LISTA</b></h3>

In [2]:
list_gods = [1,2,3,4,5,6,7,8,9,10]
list_gods

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

<h3><b>TRANSFORMANDO LA LISTA A UNA ARRAY</b></h3>

In [3]:
arreglo = np.array(list_gods)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h3><b>VERIFICAR EL TIPO DE ESTRUCTURA</b></h3>

In [4]:
type(arreglo)

numpy.ndarray

<h3><b>VERIFICAR LOS TIPOS DE DATOS DEL ARREGLO</b></h3>

In [6]:
arreglo.dtype

dtype('int32')

<h3><b>DEFINIENDO EL ARRAY DE INT32 A FLOAT32</b></h3>

In [13]:
arreglo_float32 = np.array(arreglo, dtype=np.float32)

<h3><b>TRANSFORMANDO LOS DATOS DE INT32 A FLOAT32</b></h3>

In [14]:
arreglo.astype(np.float32)
arreglo.dtype

dtype('int32')

<h3><b>FUNCION SIMILAR A RANGE PERO USANDO ARREGLOS</b></h3>

In [ ]:
arreglonuevo = np.arange(1,11)
arreglonuevo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

<h3><b>ARREGLO DE 2 EN 2 USANDO ARANGE</b></h3>

In [ ]:
arreglonuevo2 = np.arange(1,11,2)
arreglonuevo2

array([1, 3, 5, 7, 9])

<h2><b>FUNCIONES EN NUMPY</b></h2>

<h3><b>OBTENIENDO EL PROMEDIO</b></h3>

In [ ]:
promedio = np.mean(arreglo)
promedio

5.5

<h3><b>OBTENIENDO LA MEDIANA</b></h3>

In [ ]:
mediana = np.median(arreglo)
mediana

5.5

<h3><b>DESVIACION ESTANDAR DE UN ARREGLO</b></h3>

In [ ]:
desviacion_std = np.std(arreglo)
desviacion_std

2.8722813232690143

<h3><b>GENERACION DE UN ARREGLO DE 5 ELEMENTOS DE PUROS CEROS</b></h3>

In [ ]:
arreglo_de_ceros = np.zeros(5)
arreglo_de_ceros

array([0., 0., 0., 0., 0.])

<h3><b>GENERACION DE UN ARREGLO DE 10 ELEMENTOS DE PUROS UNOS</b></h3>

In [ ]:
arreglo_de_unos = np.ones(10)
arreglo_de_unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

<h3><b>TRANSFORMANDO EL ARREGLO DE UNOS DE PUNTO FLOTANTES A ENTEROS</b></h3>

In [ ]:
arreglo_int_ones = arreglo_de_unos.astype(int)
arreglo_int_ones

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

<h3><b>GENERANDO ARREGLO ALEATORIO DE 5 ELEMENTOS</b></h3>

In [23]:
arreglo_aleatorio = np.random.rand(5)
arreglo_aleatorio

array([0.9076869 , 0.32843111, 0.7682399 , 0.34152078, 0.16086627])

<h3><b>GENERANDO UNA AMTRIZ ALEATORIA DE 3X3</b></h3>

In [ ]:
matriz = np.random.rand(3,3)
matriz

array([[0.21199524, 0.93687108, 0.25522048],
       [0.51485503, 0.14025728, 0.23215116],
       [0.75224272, 0.87868184, 0.21459864]])

<h3><b>GENERANDO UN ARREGLO ALEATORIO DE 10 NUMEROS ENTEROS DE 1 AL 5</b></h3>

In [ ]:
arreglo_aleatorio2 = np.random.randint(1,5,10)
arreglo_aleatorio2

array([4, 1, 2, 1, 1, 2, 4, 4, 2, 4])

<h3><b>GENERANDO UNA MATRIZ ALEATORIA DE 5 ELEMENTOS ENTEROS DE 1 AL 100</b></h3>

In [ ]:
matriz2 = np.random.randint(1,100,(5,5))
matriz2

array([[27,  8, 88, 55, 60],
       [54, 35, 74, 32, 90],
       [26, 17, 51,  9, 18],
       [56, 19, 29, 64,  7],
       [36, 67, 51, 62, 56]])